swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"
paths:
  /populations:
    get:
      # kertoo mitä tehdään, kun tehdään HTTP-pyyntö päätepisteeseen /api/countries
      operationId: populations.read_all
      tags:
        - Populations
      summary: Read the entire set of populations, sorted by country name
      description: Read the entire set of populations, sorted by country name
      responses:
        200:
          description: Successfully read populations list operation
          schema:
            type: array
            items:
              properties:
                country_id:
                  type: string
                  description: Id of the country
                country_name:
                  type: string
                  description: Name of the country
                year_2018:
                  type: integer
                  description: Population of the country in the year 2018

  /populations/{country_id}:
    get:
      operationId: populations.read_one
      tags:
        - Populations
      summary: Read populations of one country from the list
      description: Read populations of one country from the list
      parameters:
        - name: country_id
          in: path
          description: Id of the country whose population to get
          type: string
          required: True
      responses:
        200:
          description: Succesfully read population of the country from populations list operation
          schema:
            properties:
              country_id:
                type: string
                description: Id of the country
              country_name:
                type: string
                description: Name of the country
              year_2018:
                type: integer
                description: Population of the country in the year 2018

