swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"
paths:
  /countries:
    get:
      # kertoo mitä tehdään, kun tehdään HTTP-pyyntö päätepisteeseen /api/countries
      operationId: "countries.read"
      tags:
        - "Countries"
      summary: "The countries data structure supported by the server application"
      description: "Read the list of countries and their population"
      responses:
        200:
          description: "Successful read countries list operation"
          schema:
            type: "array"
            items:
              properties:
                country_name:
                  type: "string"
                2018:
                  type: "number"